language: node_js
node_js:
- node
deploy:
  provider: gae
  keyfile: gcsAuth/gcsAuthToken.json
  project: hoovessound-173007
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_e44152bd72d8_key -iv $encrypted_e44152bd72d8_iv
  -in gcsAuthToken.json.enc -out gcsAuthToken.json -d
- openssl aes-256-cbc -K $encrypted_e44152bd72d8_key -iv $encrypted_e44152bd72d8_iv
  -in db.js.enc -out db.js -d
