language: node_js
node_js:
- node
deploy:
  provider: gae
  keyfile: gcsAuth/token.json
  project: hoovessound-173007
  on: master
before_install:
  - mkdir gcsAuth
  - openssl aes-256-cbc -K $encrypted_e44152bd72d8_key -iv $encrypted_e44152bd72d8_iv
    -in db.js.enc -out db.js -d
  - openssl aes-256-cbc -K $encrypted_e44152bd72d8_key -iv $encrypted_e44152bd72d8_iv
    -in token.json.enc -out gcsAuth/token.json -d