language: node_js
node_js:
  - node
deploy:
  provider: gae
  keyfile: token.json.enc
  project: hoovessound-173007
  on: issue#4
before_install:
- openssl aes-256-cbc -K $encrypted_e44152bd72d8_key -iv $encrypted_e44152bd72d8_iv
  -in token.json.enc -out gcsAuth/token.json -d