language: node_js
node_js:
- node
deploy:
  provider: gae
  keyfile: gcsAuth/gcsAuthToken.json
  project: hoovessound-173007
  on: master
before_install:
  - openssl aes-256-cbc -K $encrypted_e44152bd72d8_key -iv $encrypted_e44152bd72d8_iv -in encrypt_pack.tar.enc  -out encrypt_pack.tar -d
  - tar xvf encrypt_pack.tar
  - mkdir gcsAuth
  - mv gcsAuthToken.json gcsAuth/gcsAuthToken.json
  - mv db.json src/db.js
  - rm encrypt_pack.tar
